const projects = [
  {
    title: "Freshnews",
    shortDescription: "Site web & mobile d’actualité en temps réel",
    pictureURL:
      "https://res.cloudinary.com/djfrwyodt/image/upload/q_auto/v1688650130/Freshnews_jahy2f.webp",
    longDescription: [
      "Flux d’info via API : newsapi",
      "Selection du flux d’info de The Verge",
      "Possibilité de s’inscrire / se connecter",
      "Possibilité d’enregistrer des articles",
    ],
    githubFrontLink: "https://github.com/ManuPuyuelo/freshnews-frontend",
    githubBackLink: "https://github.com/ManuPuyuelo/freshnews-backend",
    URL: "https://freshnews.manupuyuelo.com/",
    technologies: [
      `/card/technologo/React.webp`,
      `/card/technologo/CSS.webp`,
      `/card/technologo/Javascript.webp`,
      `/card/technologo/Next.webp`,
      `/card/technologo/Node.webp`,
      `/card/technologo/Express.webp`,
      `/card/technologo/MongoDB.webp`,
    ],
  },
  {
    title: "Mymoviz",
    shortDescription: "Webapp de suivi de ses films préférés",
    pictureURL:
      "https://res.cloudinary.com/djfrwyodt/image/upload/q_auto/v1688650130/Mymoviz_za5nzm.webp",
    longDescription: [
      "Flux de films via API : themoviedb",
      "Possibilité de créer une wishlist",
      "Possibilité d’ajouter les films vus",
      "Possibilité d’évaluer les films vus",
    ],
    githubFrontLink: "https://github.com/ManuPuyuelo/mymoviz-frontend",
    githubBackLink: "https://github.com/ManuPuyuelo/mymoviz-backend",
    URL: "https://mymoviz.manupuyuelo.com/",
    technologies: [
      `/card/technologo/React.webp`,
      `/card/technologo/CSS.webp`,
      `/card/technologo/Javascript.webp`,
      `/card/technologo/Next.webp`,
      `/card/technologo/Node.webp`,
      `/card/technologo/Express.webp`,
    ],
  },
  {
    title: "123Soleil",
    shortDescription: "Site web de suivi météorologique",
    pictureURL: `https://res.cloudinary.com/djfrwyodt/image/upload/q_auto/v1688650130/123soleil_udgzke.webp`,
    longDescription: [
      "Flux météo via API : openweathermap",
      "Possibilité d’ajout de villes",
      "Possibilité de suppression de villes",
      "Enregistrement de la météo en bdd",
    ],
    githubFrontLink: "https://github.com/ManuPuyuelo/123soleil-frontend",
    githubBackLink: "https://github.com/ManuPuyuelo/123soleil-backend",
    URL: "https://123soleil.manupuyuelo.com/",
    technologies: [
      `/card/technologo/HTML.webp`,
      `/card/technologo/CSS.webp`,
      `/card/technologo/Javascript.webp`,
      `/card/technologo/Node.webp`,
      `/card/technologo/Express.webp`,
      `/card/technologo/MongoDB.webp`,
    ],
  },
  {
    title: "Sweetweet",
    shortDescription: "Webapp sociale d’échange d’opinion",
    pictureURL:
      "https://res.cloudinary.com/djfrwyodt/image/upload/q_auto/v1688650130/Sweetweet_qlrexl.webp",
    longDescription: [
      "Possibilité de s’inscrire / se connecter",
      "Possibilité de voir les tweets échangés",
      "Possibilité de liker les tweets",
      "Possibilité de voir les tendances via #",
    ],
    githubFrontLink: "https://github.com/ManuPuyuelo/sweetweet-frontend",
    githubBackLink: "https://github.com/ManuPuyuelo/sweetweet-backend",
    URL: "https://sweetweet.manupuyuelo.com/",
    technologies: [
      `/card/technologo/React.webp`,
      `/card/technologo/CSS.webp`,
      `/card/technologo/Javascript.webp`,
      `/card/technologo/Next.webp`,
      `/card/technologo/Node.webp`,
      `/card/technologo/Express.webp`,
      `/card/technologo/MongoDB.webp`,
    ],
  },
  {
    title: "Trainlife",
    shortDescription: "Site web & mobile de réservation de train",
    pictureURL: `https://res.cloudinary.com/djfrwyodt/image/upload/q_auto/v1688650129/Trainlife_cdezwm.webp`,
    longDescription: [
      "Possibilité de rechercher un train",
      "Possibilité de selection du trajet",
      "Possibilité d’ajout dans le panier",
      "Possibilité de ’réservation’",
    ],
    githubFrontLink: "https://github.com/ManuPuyuelo/trainlife-frontend",
    githubBackLink: "https://github.com/ManuPuyuelo/trainlife-backend",
    URL: "https://trainlife.manupuyuelo.com/",
    technologies: [
      `/card/technologo/HTML.webp`,
      `/card/technologo/CSS.webp`,
      `/card/technologo/Javascript.webp`,
      `/card/technologo/Node.webp`,
      `/card/technologo/Express.webp`,
      `/card/technologo/MongoDB.webp`,
    ],
  },
];
export default projects;
